name = "SparsityProbes"
uuid = "9960644d-b93b-4fd9-ba54-919deff2a9e3"
version = "1.0.0-DEV"
authors = ["Magnus Kroner kroner@campus.tu-berlin.de"]

[deps]
ADTypes = "47edcb42-4c32-4615-8424-f2b9edc5f35b"
SparseConnectivityTracer = "9f842d2f-2579-4b1d-911e-f412cf18a3f5"

[compat]
ADTypes = "1.22.0"
SparseConnectivityTracer = "1.2.1"
julia = "1.11"
